services:
  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: http://100.96.207.56:5000
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
